/*
  Warnings:

  - The values [DISCOUNT_CODE_DEACTIVATED] on the enum `AdminAction` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "AdminAction_new" AS ENUM ('USER_SUSPENDED', 'USER_UNSUSPENDED', 'USER_ROLE_CHANGED', 'USER_DELETED', 'USER_UPDATED', 'POST_HIDDEN', 'POST_UNHIDDEN', 'POST_DELETED', 'COMMENT_HIDDEN', 'COMMENT_UNHIDDEN', 'COMMENT_DELETED', 'CREATOR_APPLICATION_APPROVED', 'CREATOR_APPLICATION_REJECTED', 'CREATOR_STATUS_REVOKED', 'PAYMENT_REFUNDED', 'PAYMENT_VERIFIED', 'DISCOUNT_CODE_CREATED', 'DISCOUNT_CODE_UPDATED', 'DISCOUNT_CODE_DELETED', 'CREATE_GIFT', 'UPDATE_GIFT', 'DELETE_GIFT', 'REPORT_REVIEWED', 'REPORT_DISMISSED', 'REPORT_RESOLVED', 'SETTING_UPDATED', 'ANNOUNCEMENT_CREATED', 'ANNOUNCEMENT_UPDATED', 'ANNOUNCEMENT_DELETED');
ALTER TABLE "admin_activity_log" ALTER COLUMN "action" TYPE "AdminAction_new" USING ("action"::text::"AdminAction_new");
ALTER TYPE "AdminAction" RENAME TO "AdminAction_old";
ALTER TYPE "AdminAction_new" RENAME TO "AdminAction";
DROP TYPE "public"."AdminAction_old";
COMMIT;
